
FROM rustembedded/cross:armv7-unknown-linux-gnueabihf

RUN apt-get update && \
    apt-get install -y cmake g++ make git pkg-config && \
    git clone https://github.com/xianyi/OpenBLAS.git && \
    cd OpenBLAS && \
    make TARGET=ARMV7 USE_THREAD=1 USE_OPENMP=0 && \
    make install PREFIX=/usr/local/openblas

ENV RUSTFLAGS="-C target-feature=+crt-static"
ENV PKG_CONFIG_PATH="/usr/local/openblas/lib/pkgconfig"

WORKDIR /project
COPY . .

